global:
  resolve_timeout: 5m

route:
  receiver: 'email-alert'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5m

receivers:
  - name: 'email-alert'
    email_configs:
      - to: "vipdhhddh@gmail.com"
        from: "fifahayrataolahai17620044@gmail.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "fifahayrataolahai17620044@gmail.com"
        auth_password: "ayur hxdz owrf bvvw"
        require_tls: true
